# This file was generated by GoReleaser. DO NOT EDIT.
cask "backend-starter" do
  name "backend-starter"
  desc ""
  homepage "https://github.com/Walon-Foundation/backend-starter-cli"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backend-starter"

  on_macos do
    on_intel do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v#{version}/backend-starter_#{version}_macOS_amd64.tar.gz"
      sha256 "34c2c63d16bbe1f4efee52434885166557f3b682e2cd6a170cd811c52653e222"
    end
    on_arm do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v#{version}/backend-starter_#{version}_macOS_arm64.tar.gz"
      sha256 "2810e592f9b2ff1f4f1b5faf4c8adb691a0a14a8b5e67d35e04ee7dbfb480108"
    end
  end

  # No zap stanza required
end
