# This file was generated by GoReleaser. DO NOT EDIT.
cask "backend-starter" do
  desc ""
  homepage "https://github.com/Walon-Foundation/backend-starter-cli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backend-starter"

  on_macos do
    on_intel do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v0.1.2/backend-starter_0.1.2_macOS_amd64.tar.gz"
      sha256 "16af5f1167e738ffbeed6b348a6ba054b69558015ef3e8ec897811d636d64643"
    end
    on_arm do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v0.1.2/backend-starter_0.1.2_macOS_arm64.tar.gz"
      sha256 "e84faa8fa5e4c4d2d094ef43fa47b4d0f030b210457735f3212f41ac6c0e9ae1"
    end
  end

  # No zap stanza required
end
