# This file was generated by GoReleaser. DO NOT EDIT.
cask "backend-starter" do
  desc ""
  homepage "https://github.com/Walon-Foundation/backend-starter-cli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backend-starter"

  on_macos do
    on_intel do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v0.1.1/backend-starter_0.1.1_macOS_amd64.tar.gz"
      sha256 "48e5d1f5b432ef7beefb23de52b3ee637396f14766e560a3851e4691ddd400b0"
    end
    on_arm do
      url "https://github.com/Walon-Foundation/backend-starter-cli/releases/download/v0.1.1/backend-starter_0.1.1_macOS_arm64.tar.gz"
      sha256 "2a3b3f72a3b13d827d0c7829b606beac18603eee974c26646c12ea110374f22d"
    end
  end

  # No zap stanza required
end
